export const REST_API_URL = "https://cors-anywhere-axpo.onrender.com/https://www.swiggy.com/dapi/restaurants/list/v5?page_type=DESKTOP_WEB_LISTING"
export const REST_API_OFFSET_URL = "https://cors-anywhere-axpo.onrender.com/https://www.swiggy.com/dapi/restaurants/list/v5?sortBy=RELEVANCE&pageType=SEE_ALL&page_type=DESKTOP_SEE_ALL_LISTING"
export const REST_DATA_API_URL = "https://cors-anywhere-axpo.onrender.com/https://www.swiggy.com/dapi/menu/v4/full?menuId="
export const CDN_IMG_URL = "https://res.cloudinary.com/swiggy/image/upload/"
export const GIT_PROFILE_URL = "https://api.github.com/users/Pradnesh8"
export const LINKED_IN_PROFILE_URL = "https://www.linkedin.com/in/pradnesh-khedekar-40180b148/"
export const REST_API_SEARCH_URL = "https://cors-anywhere-axpo.onrender.com/https://www.swiggy.com/dapi/restaurants/search/suggest?"