export const REST_API_URL = "https://www.swiggy.com/dapi/restaurants/list/v5?lat=19.0218215&lng=73.0907&page_type=DESKTOP_WEB_LISTING"
export const REST_API_OFFSET_URL = "https://www.swiggy.com/dapi/restaurants/list/v5?lat=19.0218215&lng=73.0907&sortBy=RELEVANCE&pageType=SEE_ALL&page_type=DESKTOP_SEE_ALL_LISTING&offset="
export const REST_DATA_API_URL = "https://www.swiggy.com/dapi/menu/v4/full?lat=19.0218215&lng=73.0907&menuId="
export const CDN_IMG_URL = "https://res.cloudinary.com/swiggy/image/upload/"
export const GIT_PROFILE_URL = "https://api.github.com/users/Pradnesh8"
